SHELL := /bin/bash

.PHONY: dev prod build down code fmt lint typecheck

dev:
	@echo "Work in progress"

prod:
	@echo "Work in progress"

build:
	@echo "Work in progress"

down:
	@echo "Work in progress"

code: fmt lint typecheck

fmt:
	@echo "Work in progress"

lint:
	@echo "Work in progress"

typecheck:
	@echo "Work in progress"
